name: Check for apktool updates

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  check_apktool_updates:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
    
    - id: apktool
      uses: pozetroninc/github-action-get-latest-release@master
      with:
        owner: iBotPeaches
        repo: Apktool
        excludes: prerelease, draft
    
    - name: Test java
      run: |
        java -jar apktool/apktool.jar --version
    
    - name: Get python apktool version
      run: |
        echo "python_apktool_version=$(python -c 'import apktool; print(apktool.version())')" >> $GITHUB_ENV
    
    - name: Test version
      run: echo $python_apktool_version
